name: Backend Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build backend Docker image
      run:  docker build ./Backend --tag sep_back

    - name: Save backend Docker image
      run: |
        echo 'Starting backend image export'
        docker save --output images/sep_backend.tar sep_back

    - name: Backend docker image
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add images/sep_backend.tar
        git commit -am 'Backend Docker Image'
        git push
