name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build ./Frontend --tag sep_front
      
    - name: Save Docker image
      run: |
        echo 'Starting image export'
        docker save --output images/sep_frontend.tar sep_front

    - name: Build backend Docker image
      run:  docker build ./Backend --tag sep_back

    - name: Save backend Docker image
      run: |
        echo 'Starting backend image export'
        docker save --output images/sep_backend.tar sep_back

    - name: Commit docker images
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add images/sep_frontend.tar
        git add images/sep_backend.tar
        git commit -am 'Docker images'
        git push